### ISSUE TITLE
Cargo Workspacesを用いた依存関係の明示

### ISSUE THREAD

**Issue by shugo256** [team-azb/route-bucket-backend#62]
[cargo workspaces](https://doc.rust-jp.rs/book-ja/ch14-03-cargo-workspaces.html)を用いると、一つのプロジェクト配下に複数のcrateを共存させつつ、一つのコマンドで全体をコンパイルできるようになる

4つの層(domain, infra, usecase, controller)ごとにcrateを作れば、それぞれの`Cargo.toml`で層同士の依存関係を明示できるようになる
例えば、usecaseはdomainに依存するが、infraやcontrollerには依存しないので、以下のようになるはず
```toml
[dependencies]

domain = { path = "../domain" }
```
